import { chromium } from 'playwright';
import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { createInterface } from 'node:readline';
import { getPlatform } from './platforms.js';

type Rpc={id:string|number;method:string;params?:any};
const send=(id:any,result?:any,error?:any)=>process.stdout.write(JSON.stringify(error?{jsonrpc:'2.0',id,error}:{jsonrpc:'2.0',id,result})+'\n');
const first=async(page:any,selectors:string[])=>{for(const s of selectors){const n=page.locator(s).first();if(await n.count().catch(()=>0))return n;}return null};
async function artifact(path:string,bytes:Buffer|string){await writeFile(path,bytes);return {path,sha256:createHash('sha256').update(bytes).digest('hex')};}
async function runSearch(p:any){const platform=getPlatform(p.platformId);const out=p.outputDir;await mkdir(out,{recursive:true});const browserPath=process.env.TENDER_PLAYWRIGHT_CHROMIUM_PATH;const context=await chromium.launchPersistentContext(p.profileDir,{headless:!p.interactive,executablePath:browserPath,viewport:{width:1440,height:1000},acceptDownloads:true});let page=await context.newPage();try{await page.goto(platform.url,{waitUntil:'domcontentloaded',timeout:45000});const title=await page.title();await page.screenshot({path:join(out,'landing.png'),fullPage:true});if(p.interactive)return {status:'interactive-login-opened',platform:platform.id,title};const input=await first(page,platform.selectors.search);if(!input)return {status:'manual-review-required',reason:'search_selector_missing',platform:platform.id,landingScreenshot:join(out,'landing.png')};await input.fill(p.query);await input.press('Enter');await page.waitForTimeout(1500);await page.screenshot({path:join(out,'results.png'),fullPage:true});const body=await page.locator('body').innerText();const html=await page.content();const text=await artifact(join(out,'results.txt'),body);const source=await artifact(join(out,'results.html'),html);const result=await first(page,platform.selectors.result);if(!result)return {status:'no-result',platform:platform.id,artifacts:[text,source]};const href=await result.getAttribute('href');if(href)await page.goto(new URL(href,platform.url).toString(),{waitUntil:'domcontentloaded',timeout:45000});await page.screenshot({path:join(out,'detail.png'),fullPage:true});await page.pdf({path:join(out,'detail.pdf'),format:'A4',printBackground:true}).catch(()=>undefined);const detailText=await page.locator('body').innerText();const detail=await artifact(join(out,'detail.txt'),detailText);return {status:'success',platform:platform.id,title,artifacts:[text,source,detail],screenshots:[join(out,'landing.png'),join(out,'results.png'),join(out,'detail.png')]};}catch(e:any){await page.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>undefined);return {status:'manual-review-required',platform:platform.id,reason:e?.message||String(e),failureScreenshot:join(out,'failure.png')};}finally{await context.close();}}
async function handle(r:Rpc){if(r.method==='system.ping')return {ok:true,protocol:'ndjson-json-rpc',pid:process.pid};if(r.method==='platform.healthCheck'){const x=getPlatform(r.params.platformId);return {platform:x.id,url:x.url,loginMode:x.loginMode};}if(r.method==='platform.openLogin')return runSearch({...r.params,interactive:true,query:''});if(r.method==='platform.searchAndCapture')return runSearch({...r.params,interactive:false});throw new Error(`unsupported method ${r.method}`)}
createInterface({input:process.stdin,crlfDelay:Infinity}).on('line',async line=>{try{const r=JSON.parse(line) as Rpc;send(r.id,await handle(r));}catch(e:any){send(null,undefined,{code:-32000,message:e?.message||String(e)})}});
